/*
***************************************************************************
*                   Copyright (c) 2007 vBridge Microsystem, Inc.  
*                          Unpublished & Not for Publication
*                                 All Rights Reserved                   
*   
* File        : 
*                                                                         
* Description : *                                                                          
*
* Date        : June 9, 2007                                                           
***************************************************************************
*/


#ifdef REMOTE_CONTROL_GLOBALS
#define REMOTE_CONTROL_EXTERN
#else
#define REMOTE_CONTROL_EXTERN extern
#endif

#define STACK_SIZE_REMOTE_CONTROL    2000
REMOTE_CONTROL_EXTERN unsigned int global_control_stack[STACK_SIZE_REMOTE_CONTROL];

#ifdef TELEFORCE_DVR
#define GPIO_REMOTE_CONTROL_BIT 9
#else
#ifdef DVR_BOARD
#define GPIO_REMOTE_CONTROL_BIT 23
#else
#define GPIO_REMOTE_CONTROL_BIT 26
#endif
#endif

#define REMOTE_CONTROL_NO_KEY_BIT 0x50

#define LEADER_LOW_PULSE_WIDTH 9000
#define LEADER_HIGH_PULSE_WIDTH 4500
#define ONE_HIGH_PULSE_WIDTH 1680
#define ZERO_HIGH_PULSE_WIDTH 560
#define LOW_PULSE_WIDTH 560
#define PULSE_WIDTH_DISPERSION 300
#define LPRESS_1LOW_PULSE_WIDTH  LOW_PULSE_WIDTH
#define LPRESS_11HIGH_PULSE_WIDTH 40950
#define LPRESS_12HIGH_PULSE_WIDTH 96100
#define LPRESS_2LOW_PULSE_WIDTH  9100
#define LPRESS_2HIGH_PULSE_WIDTH 2100
#define LPRESS_FST_SND_INTERVAL 6

#define LEADER_LOW_PULSE_WIDTH_MIN     LEADER_LOW_PULSE_WIDTH-PULSE_WIDTH_DISPERSION
#define LEADER_LOW_PULSE_WIDTH_MAX     LEADER_LOW_PULSE_WIDTH+PULSE_WIDTH_DISPERSION
#define LEADER_HIGH_PULSE_WIDTH_MIN      LEADER_HIGH_PULSE_WIDTH-PULSE_WIDTH_DISPERSION
#define LEADER_HIGH_PULSE_WIDTH_MAX      LEADER_HIGH_PULSE_WIDTH+PULSE_WIDTH_DISPERSION
#define ONE_HIGH_PULSE_WIDTH_MIN        ONE_HIGH_PULSE_WIDTH-PULSE_WIDTH_DISPERSION
#define ONE_HIGH_PULSE_WIDTH_MAX        ONE_HIGH_PULSE_WIDTH+PULSE_WIDTH_DISPERSION
#define ZERO_HIGH_PULSE_WIDTH_MIN        ZERO_HIGH_PULSE_WIDTH-PULSE_WIDTH_DISPERSION
#define ZERO_HIGH_PULSE_WIDTH_MAX        ZERO_HIGH_PULSE_WIDTH+PULSE_WIDTH_DISPERSION
#define LOW_PULSE_WIDTH_MIN        LOW_PULSE_WIDTH-PULSE_WIDTH_DISPERSION
#define LOW_PULSE_WIDTH_MAX        LOW_PULSE_WIDTH+PULSE_WIDTH_DISPERSION
#define LPRESS_1LOW_PULSE_WIDTH_MIN     LPRESS_1LOW_PULSE_WIDTH-PULSE_WIDTH_DISPERSION
#define LPRESS_1LOW_PULSE_WIDTH_MAX     LPRESS_1LOW_PULSE_WIDTH+PULSE_WIDTH_DISPERSION
#define LPRESS_11HIGH_PULSE_WIDTH_MIN   LPRESS_11HIGH_PULSE_WIDTH-PULSE_WIDTH_DISPERSION
#define LPRESS_11HIGH_PULSE_WIDTH_MAX   LPRESS_11HIGH_PULSE_WIDTH+PULSE_WIDTH_DISPERSION
#define LPRESS_12HIGH_PULSE_WIDTH_MIN   LPRESS_12HIGH_PULSE_WIDTH-PULSE_WIDTH_DISPERSION*4/3
#define LPRESS_12HIGH_PULSE_WIDTH_MAX   LPRESS_12HIGH_PULSE_WIDTH+PULSE_WIDTH_DISPERSION*4/3
#define LPRESS_2LOW_PULSE_WIDTH_MIN     LPRESS_2LOW_PULSE_WIDTH-PULSE_WIDTH_DISPERSION
#define LPRESS_2LOW_PULSE_WIDTH_MAX     LPRESS_2LOW_PULSE_WIDTH+PULSE_WIDTH_DISPERSION
#define LPRESS_2HIGH_PULSE_WIDTH_MIN    LPRESS_2HIGH_PULSE_WIDTH-PULSE_WIDTH_DISPERSION
#define LPRESS_2HIGH_PULSE_WIDTH_MAX    LPRESS_2HIGH_PULSE_WIDTH+PULSE_WIDTH_DISPERSION


void TaskRemoteControl();
void RemoteControlInit();
void  RemoteControlGpioISR(void);
int RemoteControlGpioIntrInit(void);
